#!/bin/sh

{
while true
do
	feh --bg-fill --randomize $QQWM_PATH/background/*
  sleep 5m
done
}&

fcitx5 -d &

picom --experimental-backends --config $QQWM_PATH/config/picom.conf -b &

# xmodmap $QQWM_PATH/config/xmodmaprc &

slstatus &

